fix: vercel deploy error
## Vercel 部署錯誤

```sh
PrismaClientInitializationError: Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.
```

根據文檔：https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/vercel-caching-issue#a-custom-postinstall-script
我們 package.json file 下新增一行指令

```json
{
  "scripts" {
    "postinstall": "prisma generate"
  }
}
```